language: cpp
sudo: required
services: docker

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq libgraphviz-dev

script: "./autogen.sh && ./configure CXX='g++-4.9' && make"
